# Generated by Django 5.0 on 2024-01-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='upload_date',
            new_name='upload_on',
        ),
    ]
