# Generated by Django 5.0 on 2024-01-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_uploadfile_delete_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='upload_on',
            new_name='uploaded_on',
        ),
    ]
