# Generated by Django 5.0 on 2024-01-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regloginout', '0004_confirmemailtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmemailtoken',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
