FROM ubuntu:22.04

RUN apt update

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Moscow
RUN apt install -y tzdata

RUN apt install -y python3.9 python3-pip
RUN python3 -m pip install --upgrade pip

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt /usr/src/app/requirements.txt
WORKDIR /usr/src/app
RUN python3 -m pip install --no-cache-dir -r requirements.txt

COPY . /usr/src/app

ENTRYPOINT bash run.sh
